
<!DOCTYPE html>

<html lang="pt_BR">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" /><meta name="generator" content="Docutils 0.17: http://docutils.sourceforge.net/" />

    <title>Exceções embutidas &#8212; documentação Python 3.10.4</title><meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <link rel="stylesheet" href="../_static/pygments.css" type="text/css" />
    <link rel="stylesheet" href="../_static/pydoctheme.css?2022.1" type="text/css" />
    
    <script id="documentation_options" data-url_root="../" src="../_static/documentation_options.js"></script>
    <script src="../_static/jquery.js"></script>
    <script src="../_static/underscore.js"></script>
    <script src="../_static/doctools.js"></script>
    <script src="../_static/translations.js"></script>
    
    <script src="../_static/sidebar.js"></script>
    
    <link rel="search" type="application/opensearchdescription+xml"
          title="Pesquisar dentro de documentação Python 3.10.4"
          href="../_static/opensearch.xml"/>
    <link rel="author" title="Sobre esses documentos" href="../about.html" />
    <link rel="index" title="Índice" href="../genindex.html" />
    <link rel="search" title="Buscar" href="../search.html" />
    <link rel="copyright" title="Direitos autorais" href="../copyright.html" />
    <link rel="next" title="Serviços de Processamento de Texto" href="text.html" />
    <link rel="prev" title="Tipos embutidos" href="stdtypes.html" />
    <link rel="canonical" href="https://docs.python.org/3/library/exceptions.html" />
    
      
    

    
    <style>
      @media only screen {
        table.full-width-table {
            width: 100%;
        }
      }
    </style>
<link rel="shortcut icon" type="image/png" href="../_static/py.svg" />
            <script type="text/javascript" src="../_static/copybutton.js"></script>
            <script type="text/javascript" src="../_static/menu.js"></script> 

  </head>
<body>
<div class="mobile-nav">
    <input type="checkbox" id="menuToggler" class="toggler__input" aria-controls="navigation"
           aria-pressed="false" aria-expanded="false" role="button" aria-label="Menu" />
    <label for="menuToggler" class="toggler__label">
        <span></span>
    </label>
    <nav class="nav-content" role="navigation">
         <a href="https://www.python.org/" class="nav-logo">
             <img src="../_static/py.svg" alt="Logo"/>
         </a>
        <div class="version_switcher_placeholder"></div>
        <form role="search" class="search" action="../search.html" method="get">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" class="search-icon">
                <path fill-rule="nonzero"
                        d="M15.5 14h-.79l-.28-.27a6.5 6.5 0 001.48-5.34c-.47-2.78-2.79-5-5.59-5.34a6.505 6.505 0 00-7.27 7.27c.34 2.8 2.56 5.12 5.34 5.59a6.5 6.5 0 005.34-1.48l.27.28v.79l4.25 4.25c.41.41 1.08.41 1.49 0 .41-.41.41-1.08 0-1.49L15.5 14zm-6 0C7.01 14 5 11.99 5 9.5S7.01 5 9.5 5 14 7.01 14 9.5 11.99 14 9.5 14z" fill="#444"></path>
            </svg>
            <input type="text" name="q" aria-label="Busca rápida"/>
            <input type="submit" value="Ir"/>
        </form>
    </nav>
    <div class="menu-wrapper">
        <nav class="menu" role="navigation" aria-label="main navigation">
            <div class="language_switcher_placeholder"></div>
  <h3><a href="../contents.html">Tabela de Conteúdo</a></h3>
  <ul>
<li><a class="reference internal" href="#">Exceções embutidas</a><ul>
<li><a class="reference internal" href="#exception-context">Exception context</a></li>
<li><a class="reference internal" href="#inheriting-from-built-in-exceptions">Inheriting from built-in exceptions</a></li>
<li><a class="reference internal" href="#base-classes">Classes base</a></li>
<li><a class="reference internal" href="#concrete-exceptions">Exceções concretas</a><ul>
<li><a class="reference internal" href="#os-exceptions">Exceções de sistema operacional</a></li>
</ul>
</li>
<li><a class="reference internal" href="#warnings">Avisos</a></li>
<li><a class="reference internal" href="#exception-hierarchy">Hierarquia das exceções</a></li>
</ul>
</li>
</ul>

  <h4>Tópico anterior</h4>
  <p class="topless"><a href="stdtypes.html"
                        title="capítulo anterior">Tipos embutidos</a></p>
  <h4>Próximo tópico</h4>
  <p class="topless"><a href="text.html"
                        title="próximo capítulo">Serviços de Processamento de Texto</a></p>
  <div role="note" aria-label="source link">
    <h3>Esta página</h3>
    <ul class="this-page-menu">
      <li><a href="../bugs.html">Relatar um erro</a></li>
      <li>
        <a href="https://github.com/python/cpython/blob/3.10/Doc/library/exceptions.rst"
            rel="nofollow">Exibir código-fonte
        </a>
      </li>
    </ul>
  </div>
        </nav>
    </div>
</div>

  
    <div class="related" role="navigation" aria-label="related navigation">
      <h3>Navegação</h3>
      <ul>
        <li class="right" style="margin-right: 10px">
          <a href="../genindex.html" title="Índice geral"
             accesskey="I">índice</a></li>
        <li class="right" >
          <a href="../py-modindex.html" title="Índice de Módulos Python"
             >módulos</a> |</li>
        <li class="right" >
          <a href="text.html" title="Serviços de Processamento de Texto"
             accesskey="N">próximo</a> |</li>
        <li class="right" >
          <a href="stdtypes.html" title="Tipos embutidos"
             accesskey="P">anterior</a> |</li>

          <li><img src="../_static/py.svg" alt="python logo" style="vertical-align: middle; margin-top: -1px"/></li>
          <li><a href="https://www.python.org/">Python</a> &#187;</li>
          <li class="switchers">
            <div class="language_switcher_placeholder"></div>
            <div class="version_switcher_placeholder"></div>
          </li>
          <li>
              
          </li>
    <li id="cpython-language-and-version">
      <a href="../index.html">3.10.4 Documentation</a> &#187;
    </li>

          <li class="nav-item nav-item-1"><a href="index.html" accesskey="U">A Biblioteca Padrão do Python</a> &#187;</li>
        <li class="nav-item nav-item-this"><a href="">Exceções embutidas</a></li>
                <li class="right">
                    

    <div class="inline-search" role="search">
        <form class="inline-search" action="../search.html" method="get">
          <input placeholder="Busca rápida" aria-label="Busca rápida" type="text" name="q" />
          <input type="submit" value="Ir" />
          <input type="hidden" name="check_keywords" value="yes" />
          <input type="hidden" name="area" value="default" />
        </form>
    </div>
                     |
                </li>
            
      </ul>
    </div>    

    <div class="document">
      <div class="documentwrapper">
        <div class="bodywrapper">
          <div class="body" role="main">
            
  <section id="built-in-exceptions">
<span id="bltin-exceptions"></span><h1>Exceções embutidas<a class="headerlink" href="#built-in-exceptions" title="Link permanente para este título">¶</a></h1>
<p id="index-0">No Python, todas as exceções devem ser instâncias de uma classe derivada de <a class="reference internal" href="#BaseException" title="BaseException"><code class="xref py py-class docutils literal notranslate"><span class="pre">BaseException</span></code></a>. Em uma instrução <a class="reference internal" href="../reference/compound_stmts.html#try"><code class="xref std std-keyword docutils literal notranslate"><span class="pre">try</span></code></a> com uma cláusula <a class="reference internal" href="../reference/compound_stmts.html#except"><code class="xref std std-keyword docutils literal notranslate"><span class="pre">except</span></code></a> que menciona uma classe específica, essa cláusula também lida com qualquer classe de exceção derivada dessa classe (mas não com as classes de exceção a partir das quais <em>ela</em> é derivada). Duas classes de exceção que não são relacionadas por subclasse nunca são equivalentes, mesmo que tenham o mesmo nome.</p>
<p id="index-1">As exceções embutidas listadas abaixo podem ser geradas pelo interpretador ou pelas funções embutidas. Exceto onde mencionado, eles têm um “valor associado” indicando a causa detalhada do erro. Pode ser uma sequência ou uma tupla de vários itens de informação (por exemplo, um código de erro e uma sequência que explica o código). O valor associado geralmente é passado como argumentos para o construtor da classe de exceção.</p>
<p>O código do usuário pode gerar exceções embutidas. Isso pode ser usado para testar um manipulador de exceções ou para relatar uma condição de erro “exatamente como” a situação na qual o interpretador gera a mesma exceção; mas lembre-se de que nada impede o código do usuário de gerar um erro inadequado.</p>
<p>As classes de exceções embutidas podem ser usadas como subclasses para definir novas exceções; Os programadores são incentivados a derivar novas exceções da classe <a class="reference internal" href="#Exception" title="Exception"><code class="xref py py-exc docutils literal notranslate"><span class="pre">Exception</span></code></a> ou de uma de suas subclasses, e não de <a class="reference internal" href="#BaseException" title="BaseException"><code class="xref py py-exc docutils literal notranslate"><span class="pre">BaseException</span></code></a>. Mais informações sobre a definição de exceções estão disponíveis no Tutorial do Python em <a class="reference internal" href="../tutorial/errors.html#tut-userexceptions"><span class="std std-ref">Exceções definidas pelo usuário</span></a>.</p>
<section id="exception-context">
<h2>Exception context<a class="headerlink" href="#exception-context" title="Link permanente para este título">¶</a></h2>
<p>When raising a new exception while another exception
is already being handled, the new exception’s
<code class="xref py py-attr docutils literal notranslate"><span class="pre">__context__</span></code> attribute is automatically set to the handled
exception.  An exception may be handled when an <a class="reference internal" href="../reference/compound_stmts.html#except"><code class="xref std std-keyword docutils literal notranslate"><span class="pre">except</span></code></a> or
<a class="reference internal" href="../reference/compound_stmts.html#finally"><code class="xref std std-keyword docutils literal notranslate"><span class="pre">finally</span></code></a> clause, or a <a class="reference internal" href="../reference/compound_stmts.html#with"><code class="xref std std-keyword docutils literal notranslate"><span class="pre">with</span></code></a> statement, is used.</p>
<p>This implicit exception context can be
supplemented with an explicit cause by using <code class="xref std std-keyword docutils literal notranslate"><span class="pre">from</span></code> with
<a class="reference internal" href="../reference/simple_stmts.html#raise"><code class="xref std std-keyword docutils literal notranslate"><span class="pre">raise</span></code></a>:</p>
<div class="highlight-python3 notranslate"><div class="highlight"><pre><span></span><span class="k">raise</span> <span class="n">new_exc</span> <span class="kn">from</span> <span class="nn">original_exc</span>
</pre></div>
</div>
<p>A expressão a seguir <a class="reference internal" href="../reference/simple_stmts.html#raise"><code class="xref std std-keyword docutils literal notranslate"><span class="pre">from</span></code></a> deve ser uma exceção ou <code class="docutils literal notranslate"><span class="pre">None</span></code>. Ela será definida como <code class="xref py py-attr docutils literal notranslate"><span class="pre">__cause__</span></code> na exceção levantada. A definição de <code class="xref py py-attr docutils literal notranslate"><span class="pre">__cause__</span></code> também define implicitamente o atributo <code class="xref py py-attr docutils literal notranslate"><span class="pre">__suppress_context__</span></code> como <code class="docutils literal notranslate"><span class="pre">True</span></code>, de modo que o uso de <code class="docutils literal notranslate"><span class="pre">raise</span> <span class="pre">new_exc</span> <span class="pre">from</span> <span class="pre">None</span></code> substitui efetivamente a exceção antiga pela nova para fins de exibição (por exemplo, convertendo <a class="reference internal" href="#KeyError" title="KeyError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">KeyError</span></code></a> para <a class="reference internal" href="#AttributeError" title="AttributeError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">AttributeError</span></code></a>), deixando a exceção antiga disponível em <code class="xref py py-attr docutils literal notranslate"><span class="pre">__context__</span></code> para introspecção durante a depuração.</p>
<p>O código de exibição padrão do traceback mostra essas exceções encadeadas, além do traceback da própria exceção. Uma exceção explicitamente encadeada em <code class="xref py py-attr docutils literal notranslate"><span class="pre">__cause__</span></code> sempre é mostrada quando presente. Uma exceção implicitamente encadeada em <code class="xref py py-attr docutils literal notranslate"><span class="pre">__context__</span></code> é mostrada apenas se <code class="xref py py-attr docutils literal notranslate"><span class="pre">__cause__</span></code> for <a class="reference internal" href="constants.html#None" title="None"><code class="xref py py-const docutils literal notranslate"><span class="pre">None</span></code></a> e <code class="xref py py-attr docutils literal notranslate"><span class="pre">__suppress_context__</span></code> for falso.</p>
<p>Em qualquer um dos casos, a exceção em si sempre é mostrada após todas as exceções encadeadas, de modo que a linha final do traceback sempre mostre a última exceção que foi levantada.</p>
</section>
<section id="inheriting-from-built-in-exceptions">
<h2>Inheriting from built-in exceptions<a class="headerlink" href="#inheriting-from-built-in-exceptions" title="Link permanente para este título">¶</a></h2>
<p>User code can create subclasses that inherit from an exception type.
It’s recommended to only subclass one exception type at a time to avoid
any possible conflicts between how the bases handle the <code class="docutils literal notranslate"><span class="pre">args</span></code>
attribute, as well as due to possible memory layout incompatibilities.</p>
<div class="impl-detail compound">
<p><strong>CPython implementation detail:</strong> Most built-in exceptions are implemented in C for efficiency, see:
<a class="reference external" href="https://github.com/python/cpython/tree/3.10/Objects/exceptions.c">Objects/exceptions.c</a>.  Some have custom memory layouts
which makes it impossible to create a subclass that inherits from
multiple exception types. The memory layout of a type is an implementation
detail and might change between Python versions, leading to new
conflicts in the future.  Therefore, it’s recommended to avoid
subclassing multiple exception types altogether.</p>
</div>
</section>
<section id="base-classes">
<h2>Classes base<a class="headerlink" href="#base-classes" title="Link permanente para este título">¶</a></h2>
<p>As seguintes exceções são usadas principalmente como classes base para outras exceções.</p>
<dl class="py exception">
<dt id="BaseException">
<em class="property">exception </em><code class="sig-name descname">BaseException</code><a class="headerlink" href="#BaseException" title="Link permanente para esta definição">¶</a></dt>
<dd><p>A classe base para todas as exceções embutidas. Não é para ser herdada diretamente por classes definidas pelo usuário (para isso, use <a class="reference internal" href="#Exception" title="Exception"><code class="xref py py-exc docutils literal notranslate"><span class="pre">Exception</span></code></a>). Se <a class="reference internal" href="stdtypes.html#str" title="str"><code class="xref py py-func docutils literal notranslate"><span class="pre">str()</span></code></a> for chamado em uma instância desta classe, a representação do(s) argumento(s) para a instância será retornada ou a string vazia quando não houver argumentos.</p>
<dl class="py attribute">
<dt id="BaseException.args">
<code class="sig-name descname">args</code><a class="headerlink" href="#BaseException.args" title="Link permanente para esta definição">¶</a></dt>
<dd><p>A tupla de argumentos fornecidos ao construtor de exceções. Algumas exceções embutidas (como <a class="reference internal" href="#OSError" title="OSError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">OSError</span></code></a>) esperam um certo número de argumentos e atribuem um significado especial aos elementos dessa tupla, enquanto outras são normalmente chamadas apenas com uma única string que fornece uma mensagem de erro.</p>
</dd></dl>

<dl class="py method">
<dt id="BaseException.with_traceback">
<code class="sig-name descname">with_traceback</code><span class="sig-paren">(</span><em class="sig-param"><span class="n">tb</span></em><span class="sig-paren">)</span><a class="headerlink" href="#BaseException.with_traceback" title="Link permanente para esta definição">¶</a></dt>
<dd><p>Este método define <em>tb</em> como o novo traceback (situação da pilha de execução) para a exceção e retorna o objeto exceção. Era mais comumente usado antes que os recursos de encadeamento de exceções de <span class="target" id="index-17"></span><a class="pep reference external" href="https://www.python.org/dev/peps/pep-3134"><strong>PEP 3134</strong></a> se tornassem disponíveis. O exemplo a seguir mostra como podemos converter uma instância de <code class="docutils literal notranslate"><span class="pre">SomeException</span></code> em uma instância de <code class="docutils literal notranslate"><span class="pre">OtherException</span></code> enquanto preservamos o traceback. Uma vez gerado, o quadro atual é empurrado para o traceback de <code class="docutils literal notranslate"><span class="pre">OtherException</span></code>, como teria acontecido com o traceback de <code class="docutils literal notranslate"><span class="pre">SomeException</span></code> original se tivéssemos permitido que ele se propagasse para o chamador.</p>
<div class="highlight-python3 notranslate"><div class="highlight"><pre><span></span><span class="k">try</span><span class="p">:</span>
    <span class="o">...</span>
<span class="k">except</span> <span class="n">SomeException</span><span class="p">:</span>
    <span class="n">tb</span> <span class="o">=</span> <span class="n">sys</span><span class="o">.</span><span class="n">exc_info</span><span class="p">()[</span><span class="mi">2</span><span class="p">]</span>
    <span class="k">raise</span> <span class="n">OtherException</span><span class="p">(</span><span class="o">...</span><span class="p">)</span><span class="o">.</span><span class="n">with_traceback</span><span class="p">(</span><span class="n">tb</span><span class="p">)</span>
</pre></div>
</div>
</dd></dl>

</dd></dl>

<dl class="py exception">
<dt id="Exception">
<em class="property">exception </em><code class="sig-name descname">Exception</code><a class="headerlink" href="#Exception" title="Link permanente para esta definição">¶</a></dt>
<dd><p>Todas as exceções embutidas que não saem para o sistema são derivadas dessa classe. Todas as exceções definidas pelo usuário também devem ser derivadas dessa classe.</p>
</dd></dl>

<dl class="py exception">
<dt id="ArithmeticError">
<em class="property">exception </em><code class="sig-name descname">ArithmeticError</code><a class="headerlink" href="#ArithmeticError" title="Link permanente para esta definição">¶</a></dt>
<dd><p>A classe base para as exceções embutidas levantadas para vários erros aritméticos: <a class="reference internal" href="#OverflowError" title="OverflowError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">OverflowError</span></code></a>, <a class="reference internal" href="#ZeroDivisionError" title="ZeroDivisionError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">ZeroDivisionError</span></code></a>, <a class="reference internal" href="#FloatingPointError" title="FloatingPointError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">FloatingPointError</span></code></a>.</p>
</dd></dl>

<dl class="py exception">
<dt id="BufferError">
<em class="property">exception </em><code class="sig-name descname">BufferError</code><a class="headerlink" href="#BufferError" title="Link permanente para esta definição">¶</a></dt>
<dd><p>Levantado quando uma operação relacionada a <a class="reference internal" href="../c-api/buffer.html#bufferobjects"><span class="std std-ref">buffer</span></a> não puder ser realizada.</p>
</dd></dl>

<dl class="py exception">
<dt id="LookupError">
<em class="property">exception </em><code class="sig-name descname">LookupError</code><a class="headerlink" href="#LookupError" title="Link permanente para esta definição">¶</a></dt>
<dd><p>A classe base para as exceções levantadas quando uma chave ou índice usado em um mapeamento ou sequência é inválido: <a class="reference internal" href="#IndexError" title="IndexError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">IndexError</span></code></a>, <a class="reference internal" href="#KeyError" title="KeyError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">KeyError</span></code></a>. Isso pode ser levantado diretamente por <a class="reference internal" href="codecs.html#codecs.lookup" title="codecs.lookup"><code class="xref py py-func docutils literal notranslate"><span class="pre">codecs.lookup()</span></code></a>.</p>
</dd></dl>

</section>
<section id="concrete-exceptions">
<h2>Exceções concretas<a class="headerlink" href="#concrete-exceptions" title="Link permanente para este título">¶</a></h2>
<p>As seguintes exceções são as que geralmente são levantados.</p>
<dl class="py exception">
<dt id="AssertionError">
<em class="property">exception </em><code class="sig-name descname">AssertionError</code><a class="headerlink" href="#AssertionError" title="Link permanente para esta definição">¶</a></dt>
<dd><p id="index-3">Levantado quando uma instrução <a class="reference internal" href="../reference/simple_stmts.html#assert"><code class="xref std std-keyword docutils literal notranslate"><span class="pre">assert</span></code></a> falha.</p>
</dd></dl>

<dl class="py exception">
<dt id="AttributeError">
<em class="property">exception </em><code class="sig-name descname">AttributeError</code><a class="headerlink" href="#AttributeError" title="Link permanente para esta definição">¶</a></dt>
<dd><p>Levantado quando uma referência de atributo (consulte <a class="reference internal" href="../reference/expressions.html#attribute-references"><span class="std std-ref">Attribute references</span></a>) ou atribuição falha. (Quando um objeto não oferece suporte a referências ou atribuições de atributos, <a class="reference internal" href="#TypeError" title="TypeError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">TypeError</span></code></a> é levantado.)</p>
<p>Os atributos <code class="xref py py-attr docutils literal notranslate"><span class="pre">name</span></code> e <code class="xref py py-attr docutils literal notranslate"><span class="pre">obj</span></code> podem ser configurados usando argumentos somente-nomeados para o construtor. Quando configurados, eles representam o nome do atributo que se tentou acessar e do objeto que foi acessado por esse atributo, respectivamente.</p>
<div class="versionchanged">
<p><span class="versionmodified changed">Alterado na versão 3.10: </span>Adicionado os atributos <code class="xref py py-attr docutils literal notranslate"><span class="pre">name</span></code> e <code class="xref py py-attr docutils literal notranslate"><span class="pre">obj</span></code>.</p>
</div>
</dd></dl>

<dl class="py exception">
<dt id="EOFError">
<em class="property">exception </em><code class="sig-name descname">EOFError</code><a class="headerlink" href="#EOFError" title="Link permanente para esta definição">¶</a></dt>
<dd><p>Levantado quando a função <a class="reference internal" href="functions.html#input" title="input"><code class="xref py py-func docutils literal notranslate"><span class="pre">input()</span></code></a> atinge uma condição de fim de arquivo (EOF) sem ler nenhum dado. (Note: os métodos <code class="xref py py-meth docutils literal notranslate"><span class="pre">io.IOBase.read()</span></code> e <a class="reference internal" href="io.html#io.IOBase.readline" title="io.IOBase.readline"><code class="xref py py-meth docutils literal notranslate"><span class="pre">io.IOBase.readline()</span></code></a> retornam uma string vazia quando pressionam o EOF.)</p>
</dd></dl>

<dl class="py exception">
<dt id="FloatingPointError">
<em class="property">exception </em><code class="sig-name descname">FloatingPointError</code><a class="headerlink" href="#FloatingPointError" title="Link permanente para esta definição">¶</a></dt>
<dd><p>Não usado atualmente.</p>
</dd></dl>

<dl class="py exception">
<dt id="GeneratorExit">
<em class="property">exception </em><code class="sig-name descname">GeneratorExit</code><a class="headerlink" href="#GeneratorExit" title="Link permanente para esta definição">¶</a></dt>
<dd><p>Levantado quando um <a class="reference internal" href="../glossary.html#term-generator"><span class="xref std std-term">gerador</span></a> ou uma <a class="reference internal" href="../glossary.html#term-coroutine"><span class="xref std std-term">corrotina</span></a> está fechado(a); veja <a class="reference internal" href="../reference/expressions.html#generator.close" title="generator.close"><code class="xref py py-meth docutils literal notranslate"><span class="pre">generator.close()</span></code></a> e <a class="reference internal" href="../reference/datamodel.html#coroutine.close" title="coroutine.close"><code class="xref py py-meth docutils literal notranslate"><span class="pre">coroutine.close()</span></code></a>. Herda diretamente de <a class="reference internal" href="#BaseException" title="BaseException"><code class="xref py py-exc docutils literal notranslate"><span class="pre">BaseException</span></code></a> em vez de <a class="reference internal" href="#Exception" title="Exception"><code class="xref py py-exc docutils literal notranslate"><span class="pre">Exception</span></code></a>, já que tecnicamente não é um erro.</p>
</dd></dl>

<dl class="py exception">
<dt id="ImportError">
<em class="property">exception </em><code class="sig-name descname">ImportError</code><a class="headerlink" href="#ImportError" title="Link permanente para esta definição">¶</a></dt>
<dd><p>Levantada quando a instrução <a class="reference internal" href="../reference/simple_stmts.html#import"><code class="xref std std-keyword docutils literal notranslate"><span class="pre">import</span></code></a> tem problemas ao tentar carregar um módulo. Também é gerado quando o “from list” em <code class="docutils literal notranslate"><span class="pre">from</span> <span class="pre">...</span> <span class="pre">import</span></code> tem um nome que não pode ser encontrado.</p>
<p>Os atributos <code class="xref py py-attr docutils literal notranslate"><span class="pre">name</span></code> e <code class="xref py py-attr docutils literal notranslate"><span class="pre">path</span></code> podem ser configurados usando argumentos somente-nomeados para o construtor. Quando configurados, eles representam o nome do módulo que foi tentado ser importado e o caminho para qualquer arquivo que acionou a exceção, respectivamente.</p>
<div class="versionchanged">
<p><span class="versionmodified changed">Alterado na versão 3.3: </span>Adicionados os atributos <code class="xref py py-attr docutils literal notranslate"><span class="pre">name</span></code> e <code class="xref py py-attr docutils literal notranslate"><span class="pre">path</span></code>.</p>
</div>
</dd></dl>

<dl class="py exception">
<dt id="ModuleNotFoundError">
<em class="property">exception </em><code class="sig-name descname">ModuleNotFoundError</code><a class="headerlink" href="#ModuleNotFoundError" title="Link permanente para esta definição">¶</a></dt>
<dd><p>Uma subclasse de <a class="reference internal" href="#ImportError" title="ImportError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">ImportError</span></code></a> que é levantada por <a class="reference internal" href="../reference/simple_stmts.html#import"><code class="xref std std-keyword docutils literal notranslate"><span class="pre">import</span></code></a> quando um módulo não pôde ser localizado. Também é levantada quando <code class="docutils literal notranslate"><span class="pre">None</span></code> é encontrado em <a class="reference internal" href="sys.html#sys.modules" title="sys.modules"><code class="xref py py-data docutils literal notranslate"><span class="pre">sys.modules</span></code></a>.</p>
<div class="versionadded">
<p><span class="versionmodified added">Novo na versão 3.6.</span></p>
</div>
</dd></dl>

<dl class="py exception">
<dt id="IndexError">
<em class="property">exception </em><code class="sig-name descname">IndexError</code><a class="headerlink" href="#IndexError" title="Link permanente para esta definição">¶</a></dt>
<dd><p>Levantada quando um índice de alguma sequência está fora do intervalo.  (Índices de fatia são truncados silenciosamente para cair num intervalo permitido; se um índice não for um inteiro, <a class="reference internal" href="#TypeError" title="TypeError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">TypeError</span></code></a> é levantada.)</p>
</dd></dl>

<dl class="py exception">
<dt id="KeyError">
<em class="property">exception </em><code class="sig-name descname">KeyError</code><a class="headerlink" href="#KeyError" title="Link permanente para esta definição">¶</a></dt>
<dd><p>Levantada quando uma chave de mapeamento (dicionário) não é encontrada no conjunto de chaves existentes.</p>
</dd></dl>

<dl class="py exception">
<dt id="KeyboardInterrupt">
<em class="property">exception </em><code class="sig-name descname">KeyboardInterrupt</code><a class="headerlink" href="#KeyboardInterrupt" title="Link permanente para esta definição">¶</a></dt>
<dd><p>Levantada quando um usuário aperta a tecla de interrupção (normalmente <kbd class="kbd docutils literal notranslate"><kbd class="kbd docutils literal notranslate">Control</kbd>-<kbd class="kbd docutils literal notranslate">C</kbd></kbd> ou <kbd class="kbd docutils literal notranslate">Delete</kbd>).  Durante a execução, uma checagem de interrupção é feita regularmente. A exceção herda de <a class="reference internal" href="#BaseException" title="BaseException"><code class="xref py py-exc docutils literal notranslate"><span class="pre">BaseException</span></code></a> para que não seja capturada acidentalmente por códigos que tratam <a class="reference internal" href="#Exception" title="Exception"><code class="xref py py-exc docutils literal notranslate"><span class="pre">Exception</span></code></a> e assim evita que o interpretador saia.</p>
<div class="admonition note">
<p class="admonition-title">Nota</p>
<p>Catching a <a class="reference internal" href="#KeyboardInterrupt" title="KeyboardInterrupt"><code class="xref py py-exc docutils literal notranslate"><span class="pre">KeyboardInterrupt</span></code></a> requires special consideration.
Because it can be raised at unpredictable points, it may, in some
circumstances, leave the running program in an inconsistent state. It is
generally best to allow <a class="reference internal" href="#KeyboardInterrupt" title="KeyboardInterrupt"><code class="xref py py-exc docutils literal notranslate"><span class="pre">KeyboardInterrupt</span></code></a> to end the program as
quickly as possible or avoid raising it entirely. (See
<a class="reference internal" href="signal.html#handlers-and-exceptions"><span class="std std-ref">Note on Signal Handlers and Exceptions</span></a>.)</p>
</div>
</dd></dl>

<dl class="py exception">
<dt id="MemoryError">
<em class="property">exception </em><code class="sig-name descname">MemoryError</code><a class="headerlink" href="#MemoryError" title="Link permanente para esta definição">¶</a></dt>
<dd><p>Levantada quando uma operação fica sem memória mas a situação ainda pode ser recuperada (excluindo alguns objetos).  O valor associado é uma string que indica o tipo de operação (interna) que ficou sem memória. Observe que, por causa da arquitetura de gerenciamento de memória subjacente (função <code class="xref c c-func docutils literal notranslate"><span class="pre">malloc()</span></code> do C), o interpretador pode não ser capaz de se recuperar completamente da situação; no entanto, levanta uma exceção para que um traceback possa ser impresso, no caso de um outro programa ser a causa.</p>
</dd></dl>

<dl class="py exception">
<dt id="NameError">
<em class="property">exception </em><code class="sig-name descname">NameError</code><a class="headerlink" href="#NameError" title="Link permanente para esta definição">¶</a></dt>
<dd><p>Levantada quando um nome local ou global não é encontrado. Isso se aplica apenas a nomes não qualificados. O valor associado é uma mensagem de erro que inclui o nome que não pode ser encontrado.</p>
<p>O atributo <code class="xref py py-attr docutils literal notranslate"><span class="pre">name</span></code> pode ser definido usando um argumento somente-nomeado para o construtor. Quando definido, representa o nome da variável que foi tentada ser acessada.</p>
<div class="versionchanged">
<p><span class="versionmodified changed">Alterado na versão 3.10: </span>Adicionado o atributo <code class="xref py py-attr docutils literal notranslate"><span class="pre">name</span></code>.</p>
</div>
</dd></dl>

<dl class="py exception">
<dt id="NotImplementedError">
<em class="property">exception </em><code class="sig-name descname">NotImplementedError</code><a class="headerlink" href="#NotImplementedError" title="Link permanente para esta definição">¶</a></dt>
<dd><p>Essa exceção é derivada da <a class="reference internal" href="#RuntimeError" title="RuntimeError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">RuntimeError</span></code></a>.  Em classes base, definidas pelo usuário, os métodos abstratos devem gerar essa exceção quando requerem que classes derivadas substituam o método, ou enquanto a classe está sendo desenvolvida, para indicar que a implementação real ainda precisa ser adicionada.</p>
<div class="admonition note">
<p class="admonition-title">Nota</p>
<p>Não deve ser usada para indicar que um operador ou método não será mais suportado – nesse caso deixe o operador / método indefinido ou, se é uma subclasse, defina-o como <a class="reference internal" href="constants.html#None" title="None"><code class="xref py py-data docutils literal notranslate"><span class="pre">None</span></code></a>.</p>
</div>
<div class="admonition note">
<p class="admonition-title">Nota</p>
<p><code class="docutils literal notranslate"><span class="pre">NotImplementedError</span></code> e <code class="docutils literal notranslate"><span class="pre">NotImplemented</span></code> não são intercambiáveis, mesmo que tenham nomes e propósitos similares.  Veja <a class="reference internal" href="constants.html#NotImplemented" title="NotImplemented"><code class="xref py py-data docutils literal notranslate"><span class="pre">NotImplemented</span></code></a> para detalhes e casos de uso.</p>
</div>
</dd></dl>

<dl class="py exception">
<dt id="OSError">
<em class="property">exception </em><code class="sig-name descname">OSError</code><span class="sig-paren">(</span><span class="optional">[</span><em class="sig-param">arg</em><span class="optional">]</span><span class="sig-paren">)</span><a class="headerlink" href="#OSError" title="Link permanente para esta definição">¶</a></dt>
<dt>
<em class="property">exception </em><code class="sig-name descname">OSError</code><span class="sig-paren">(</span><em class="sig-param">errno</em>, <em class="sig-param">strerror</em><span class="optional">[</span>, <em class="sig-param">filename</em><span class="optional">[</span>, <em class="sig-param">winerror</em><span class="optional">[</span>, <em class="sig-param">filename2</em><span class="optional">]</span><span class="optional">]</span><span class="optional">]</span><span class="sig-paren">)</span></dt>
<dd><p id="index-4">Esta exceção é levantada quando uma função do sistema retorna um erro relacionado ao sistema, incluindo falhas do tipo E/S como “file not found” ou “disk full” (não para tipos de argumentos não permitidos ou outro erro acessório).</p>
<p>A segunda forma do construtor definir os atributos correspondentes, descritos abaixo.  Os atributos usarão o valor padrão <a class="reference internal" href="constants.html#None" title="None"><code class="xref py py-const docutils literal notranslate"><span class="pre">None</span></code></a> se não forem especificados.  Por compatibilidade com versões anteriores, se três argumentos são passados, o atributo <a class="reference internal" href="#BaseException.args" title="BaseException.args"><code class="xref py py-attr docutils literal notranslate"><span class="pre">args</span></code></a> contêm somente uma tupla de 2 elementos, os dois primeiros argumentos do construtor.</p>
<p>O construtor geralmente retorna uma subclasse de <a class="reference internal" href="#OSError" title="OSError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">OSError</span></code></a>, como descrito abaixo em <a class="reference internal" href="#os-exceptions">OS exceptions</a> .  A subclasse particular depende do valor final de <a class="reference internal" href="#OSError.errno" title="OSError.errno"><code class="xref py py-attr docutils literal notranslate"><span class="pre">errno</span></code></a>.  Este comportamento ocorre apenas durante a construção direta ou por meio de um apelido de <a class="reference internal" href="#OSError" title="OSError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">OSError</span></code></a>, e não é herdado na criação de subclasses.</p>
<dl class="py attribute">
<dt id="OSError.errno">
<code class="sig-name descname">errno</code><a class="headerlink" href="#OSError.errno" title="Link permanente para esta definição">¶</a></dt>
<dd><p>Um código de erro numérico da variável C <code class="xref c c-data docutils literal notranslate"><span class="pre">errno</span></code>.</p>
</dd></dl>

<dl class="py attribute">
<dt id="OSError.winerror">
<code class="sig-name descname">winerror</code><a class="headerlink" href="#OSError.winerror" title="Link permanente para esta definição">¶</a></dt>
<dd><p>No Windows, isso fornece o código de erro nativo do Windows. O atributo <a class="reference internal" href="#OSError.errno" title="OSError.errno"><code class="xref py py-attr docutils literal notranslate"><span class="pre">errno</span></code></a> é então uma tradução aproximada, em termos POSIX, desse código de erro nativo.</p>
<p>No Windows, se o argumento de construtor <em>winerror</em> for um inteiro, o atributo <a class="reference internal" href="#OSError.errno" title="OSError.errno"><code class="xref py py-attr docutils literal notranslate"><span class="pre">errno</span></code></a> é determinado a partir do código de erro do Windows e o argumento <em>errno</em> é ignorado. Em outras plataformas, o argumento <em>winerror</em> é ignorado e o atributo <a class="reference internal" href="#OSError.winerror" title="OSError.winerror"><code class="xref py py-attr docutils literal notranslate"><span class="pre">winerror</span></code></a> não existe.</p>
</dd></dl>

<dl class="py attribute">
<dt id="OSError.strerror">
<code class="sig-name descname">strerror</code><a class="headerlink" href="#OSError.strerror" title="Link permanente para esta definição">¶</a></dt>
<dd><p>A mensagem de erro correspondente, conforme fornecida pelo sistema operacional. É formatada pelas funções C <code class="xref c c-func docutils literal notranslate"><span class="pre">perror()</span></code> no POSIX e <code class="xref c c-func docutils literal notranslate"><span class="pre">FormatMessage()</span></code> no Windows.</p>
</dd></dl>

<dl class="py attribute">
<dt id="OSError.filename">
<code class="sig-name descname">filename</code><a class="headerlink" href="#OSError.filename" title="Link permanente para esta definição">¶</a></dt>
<dt id="OSError.filename2">
<code class="sig-name descname">filename2</code><a class="headerlink" href="#OSError.filename2" title="Link permanente para esta definição">¶</a></dt>
<dd><p>Para exceções que envolvem um caminho do sistema de arquivos (como <a class="reference internal" href="functions.html#open" title="open"><code class="xref py py-func docutils literal notranslate"><span class="pre">open()</span></code></a> ou <a class="reference internal" href="os.html#os.unlink" title="os.unlink"><code class="xref py py-func docutils literal notranslate"><span class="pre">os.unlink()</span></code></a>), <a class="reference internal" href="#OSError.filename" title="OSError.filename"><code class="xref py py-attr docutils literal notranslate"><span class="pre">filename</span></code></a> é o nome do arquivo passado para a função. Para funções que envolvem dois caminhos de sistema de arquivos (como <a class="reference internal" href="os.html#os.rename" title="os.rename"><code class="xref py py-func docutils literal notranslate"><span class="pre">os.rename()</span></code></a>), <a class="reference internal" href="#OSError.filename2" title="OSError.filename2"><code class="xref py py-attr docutils literal notranslate"><span class="pre">filename2</span></code></a> corresponde ao segundo nome de arquivo passado para a função.</p>
</dd></dl>

<div class="versionchanged">
<p><span class="versionmodified changed">Alterado na versão 3.3: </span><a class="reference internal" href="#EnvironmentError" title="EnvironmentError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">EnvironmentError</span></code></a>, <a class="reference internal" href="#IOError" title="IOError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">IOError</span></code></a>, <a class="reference internal" href="#WindowsError" title="WindowsError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">WindowsError</span></code></a>, <a class="reference internal" href="socket.html#socket.error" title="socket.error"><code class="xref py py-exc docutils literal notranslate"><span class="pre">socket.error</span></code></a>, <a class="reference internal" href="select.html#select.error" title="select.error"><code class="xref py py-exc docutils literal notranslate"><span class="pre">select.error</span></code></a> e <code class="xref py py-exc docutils literal notranslate"><span class="pre">mmap.error</span></code> foram fundidos em <a class="reference internal" href="#OSError" title="OSError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">OSError</span></code></a>, e o construtor pode retornar uma subclasse.</p>
</div>
<div class="versionchanged">
<p><span class="versionmodified changed">Alterado na versão 3.4: </span>O atributo <a class="reference internal" href="#OSError.filename" title="OSError.filename"><code class="xref py py-attr docutils literal notranslate"><span class="pre">filename</span></code></a> agora é o nome do arquivo original passado para a função, ao invés do nome codificado ou decodificado da <a class="reference internal" href="../glossary.html#term-filesystem-encoding-and-error-handler"><span class="xref std std-term">tratador de erros e codificação do sistema de arquivos</span></a>. Além disso, o argumento e o atributo de construtor <em>filename2</em> foi adicionado.</p>
</div>
</dd></dl>

<dl class="py exception">
<dt id="OverflowError">
<em class="property">exception </em><code class="sig-name descname">OverflowError</code><a class="headerlink" href="#OverflowError" title="Link permanente para esta definição">¶</a></dt>
<dd><p>Levantada quando o resultado de uma operação aritmética é muito grande para ser representada. Isso não pode ocorrer para inteiros (que prefere levantar <a class="reference internal" href="#MemoryError" title="MemoryError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">MemoryError</span></code></a> a desistir). No entanto, por motivos históricos, OverflowError às vezes é levantada para inteiros que estão fora de um intervalo obrigatório. Devido à falta de padronização do tratamento de exceção de ponto flutuante em C, a maioria das operações de ponto flutuante não são verificadas.</p>
</dd></dl>

<dl class="py exception">
<dt id="RecursionError">
<em class="property">exception </em><code class="sig-name descname">RecursionError</code><a class="headerlink" href="#RecursionError" title="Link permanente para esta definição">¶</a></dt>
<dd><p>Esta exceção é derivada de <a class="reference internal" href="#RuntimeError" title="RuntimeError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">RuntimeError</span></code></a>. É levantada quando o interpretador detecta que a profundidade máxima de recursão (veja <a class="reference internal" href="sys.html#sys.getrecursionlimit" title="sys.getrecursionlimit"><code class="xref py py-func docutils literal notranslate"><span class="pre">sys.getrecursionlimit()</span></code></a>) foi excedida.</p>
<div class="versionadded">
<p><span class="versionmodified added">Novo na versão 3.5: </span>Anteriormente, uma <a class="reference internal" href="#RuntimeError" title="RuntimeError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">RuntimeError</span></code></a> simples era levantada.</p>
</div>
</dd></dl>

<dl class="py exception">
<dt id="ReferenceError">
<em class="property">exception </em><code class="sig-name descname">ReferenceError</code><a class="headerlink" href="#ReferenceError" title="Link permanente para esta definição">¶</a></dt>
<dd><p>Esta exceção é levantada quando um intermediário de referência fraca, criado pela função <a class="reference internal" href="weakref.html#weakref.proxy" title="weakref.proxy"><code class="xref py py-func docutils literal notranslate"><span class="pre">weakref.proxy()</span></code></a>, é usado para acessar um atributo do referente após ter sido coletado como lixo. Para mais informações sobre referências fracas, veja o módulo <a class="reference internal" href="weakref.html#module-weakref" title="weakref: Support for weak references and weak dictionaries."><code class="xref py py-mod docutils literal notranslate"><span class="pre">weakref</span></code></a>.</p>
</dd></dl>

<dl class="py exception">
<dt id="RuntimeError">
<em class="property">exception </em><code class="sig-name descname">RuntimeError</code><a class="headerlink" href="#RuntimeError" title="Link permanente para esta definição">¶</a></dt>
<dd><p>Levantada quando um erro é detectado e não se encaixa em nenhuma das outras categorias. O valor associado é uma string indicando o que precisamente deu errado.</p>
</dd></dl>

<dl class="py exception">
<dt id="StopIteration">
<em class="property">exception </em><code class="sig-name descname">StopIteration</code><a class="headerlink" href="#StopIteration" title="Link permanente para esta definição">¶</a></dt>
<dd><p>Levantada pela função embutida <a class="reference internal" href="functions.html#next" title="next"><code class="xref py py-func docutils literal notranslate"><span class="pre">next()</span></code></a> e o método <a class="reference internal" href="stdtypes.html#iterator.__next__" title="iterator.__next__"><code class="xref py py-meth docutils literal notranslate"><span class="pre">__next__()</span></code></a> de um <a class="reference internal" href="../glossary.html#term-iterator"><span class="xref std std-term">iterador</span></a> para sinalizar que não há mais itens produzidos pelo iterador.</p>
<p>O objeto exceção tem um único atributo <code class="xref py py-attr docutils literal notranslate"><span class="pre">value</span></code>, que é fornecido como um argumento ao construir a exceção, e o padrão é <a class="reference internal" href="constants.html#None" title="None"><code class="xref py py-const docutils literal notranslate"><span class="pre">None</span></code></a>.</p>
<p>Quando uma função <a class="reference internal" href="../glossary.html#term-generator"><span class="xref std std-term">geradora</span></a> ou <a class="reference internal" href="../glossary.html#term-coroutine"><span class="xref std std-term">corrotina</span></a> retorna, uma nova instância <a class="reference internal" href="#StopIteration" title="StopIteration"><code class="xref py py-exc docutils literal notranslate"><span class="pre">StopIteration</span></code></a> é levantada, e o valor retornado pela função é usado como o parâmetro <code class="xref py py-attr docutils literal notranslate"><span class="pre">value</span></code> para o construtor da exceção.</p>
<p>Se um código gerador direta ou indiretamente levantar <a class="reference internal" href="#StopIteration" title="StopIteration"><code class="xref py py-exc docutils literal notranslate"><span class="pre">StopIteration</span></code></a>, ele é convertido em uma <a class="reference internal" href="#RuntimeError" title="RuntimeError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">RuntimeError</span></code></a> (mantendo o <a class="reference internal" href="#StopIteration" title="StopIteration"><code class="xref py py-exc docutils literal notranslate"><span class="pre">StopIteration</span></code></a> como a nova causa da exceção).</p>
<div class="versionchanged">
<p><span class="versionmodified changed">Alterado na versão 3.3: </span>Adicionado o atributo <code class="docutils literal notranslate"><span class="pre">value</span></code> e a capacidade das funções geradoras de usá-lo para retornar um valor.</p>
</div>
<div class="versionchanged">
<p><span class="versionmodified changed">Alterado na versão 3.5: </span>Introduzida a transformação RuntimeError via <code class="docutils literal notranslate"><span class="pre">from</span> <span class="pre">__future__</span> <span class="pre">import</span> <span class="pre">generator_stop</span></code>, consulte <span class="target" id="index-18"></span><a class="pep reference external" href="https://www.python.org/dev/peps/pep-0479"><strong>PEP 479</strong></a>.</p>
</div>
<div class="versionchanged">
<p><span class="versionmodified changed">Alterado na versão 3.7: </span>Habilita <span class="target" id="index-19"></span><a class="pep reference external" href="https://www.python.org/dev/peps/pep-0479"><strong>PEP 479</strong></a> para todo o código por padrão: um erro <a class="reference internal" href="#StopIteration" title="StopIteration"><code class="xref py py-exc docutils literal notranslate"><span class="pre">StopIteration</span></code></a> levantado em um gerador é transformado em uma <a class="reference internal" href="#RuntimeError" title="RuntimeError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">RuntimeError</span></code></a>.</p>
</div>
</dd></dl>

<dl class="py exception">
<dt id="StopAsyncIteration">
<em class="property">exception </em><code class="sig-name descname">StopAsyncIteration</code><a class="headerlink" href="#StopAsyncIteration" title="Link permanente para esta definição">¶</a></dt>
<dd><p>Deve ser levantada pelo método <code class="xref py py-meth docutils literal notranslate"><span class="pre">__anext__()</span></code> de um objeto <a class="reference internal" href="../glossary.html#term-asynchronous-iterator"><span class="xref std std-term">iterador assíncrono</span></a> para parar a iteração.</p>
<div class="versionadded">
<p><span class="versionmodified added">Novo na versão 3.5.</span></p>
</div>
</dd></dl>

<dl class="py exception">
<dt id="SyntaxError">
<em class="property">exception </em><code class="sig-name descname">SyntaxError</code><span class="sig-paren">(</span><em class="sig-param"><span class="n">message</span></em>, <em class="sig-param"><span class="n">details</span></em><span class="sig-paren">)</span><a class="headerlink" href="#SyntaxError" title="Link permanente para esta definição">¶</a></dt>
<dd><p>Levantada quando o analisador encontra um erro de sintaxe. Isso pode ocorrer em uma instrução <a class="reference internal" href="../reference/simple_stmts.html#import"><code class="xref std std-keyword docutils literal notranslate"><span class="pre">import</span></code></a>, em uma chamada às funções embutidas <a class="reference internal" href="functions.html#compile" title="compile"><code class="xref py py-func docutils literal notranslate"><span class="pre">compile()</span></code></a>, <a class="reference internal" href="functions.html#exec" title="exec"><code class="xref py py-func docutils literal notranslate"><span class="pre">exec()</span></code></a> ou <a class="reference internal" href="functions.html#eval" title="eval"><code class="xref py py-func docutils literal notranslate"><span class="pre">eval()</span></code></a>, ou ao ler o script inicial ou entrada padrão (também interativamente).</p>
<p>A função <a class="reference internal" href="stdtypes.html#str" title="str"><code class="xref py py-func docutils literal notranslate"><span class="pre">str()</span></code></a> da instância de exceção retorna apenas a mensagem de erro. Detalhes é uma tupla cujos membros também estão disponíveis como atributos separados.</p>
<dl class="py attribute">
<dt id="SyntaxError.filename">
<code class="sig-name descname">filename</code><a class="headerlink" href="#SyntaxError.filename" title="Link permanente para esta definição">¶</a></dt>
<dd><p>O nome do arquivo em que ocorreu o erro de sintaxe.</p>
</dd></dl>

<dl class="py attribute">
<dt id="SyntaxError.lineno">
<code class="sig-name descname">lineno</code><a class="headerlink" href="#SyntaxError.lineno" title="Link permanente para esta definição">¶</a></dt>
<dd><p>Em qual número de linha no arquivo o erro ocorreu. Este é indexado em 1: a primeira linha no arquivo tem um <code class="docutils literal notranslate"><span class="pre">lineno</span></code> de 1.</p>
</dd></dl>

<dl class="py attribute">
<dt id="SyntaxError.offset">
<code class="sig-name descname">offset</code><a class="headerlink" href="#SyntaxError.offset" title="Link permanente para esta definição">¶</a></dt>
<dd><p>A coluna da linha em que ocorreu o erro. Este é indexado em 1: o primeiro caractere na linha tem um <code class="docutils literal notranslate"><span class="pre">offset</span></code> de 1.</p>
</dd></dl>

<dl class="py attribute">
<dt id="SyntaxError.text">
<code class="sig-name descname">text</code><a class="headerlink" href="#SyntaxError.text" title="Link permanente para esta definição">¶</a></dt>
<dd><p>O texto do código-fonte envolvido no erro.</p>
</dd></dl>

<dl class="py attribute">
<dt id="SyntaxError.end_lineno">
<code class="sig-name descname">end_lineno</code><a class="headerlink" href="#SyntaxError.end_lineno" title="Link permanente para esta definição">¶</a></dt>
<dd><p>Em qual número de linha no arquivo o erro ocorrido termina. Este é indexado em 1: a primeira linha no arquivo tem um <code class="docutils literal notranslate"><span class="pre">lineno</span></code> de 1.</p>
</dd></dl>

<dl class="py attribute">
<dt id="SyntaxError.end_offset">
<code class="sig-name descname">end_offset</code><a class="headerlink" href="#SyntaxError.end_offset" title="Link permanente para esta definição">¶</a></dt>
<dd><p>A coluna da linha final em que erro ocorrido finaliza Este é indexado em 1: o primeiro caractere na linha tem um <code class="docutils literal notranslate"><span class="pre">offset</span></code> de 1.</p>
</dd></dl>

<p>Para erros em campos de f-string, a mensagem é prefixada por “f-string: ” e os “offsets” são deslocamentos em um texto construído a partir da expressão de substituição. Por exemplo, compilar o campo f’Bad {a b}’ resulta neste atributo de argumentos: (‘f-string: …’, (‘’, 1, 2, ‘(a b)n’, 1, 5)).</p>
<div class="versionchanged">
<p><span class="versionmodified changed">Alterado na versão 3.10: </span>Adicionado os atributos <a class="reference internal" href="#SyntaxError.end_lineno" title="SyntaxError.end_lineno"><code class="xref py py-attr docutils literal notranslate"><span class="pre">end_lineno</span></code></a> e <a class="reference internal" href="#SyntaxError.end_offset" title="SyntaxError.end_offset"><code class="xref py py-attr docutils literal notranslate"><span class="pre">end_offset</span></code></a>.</p>
</div>
</dd></dl>

<dl class="py exception">
<dt id="IndentationError">
<em class="property">exception </em><code class="sig-name descname">IndentationError</code><a class="headerlink" href="#IndentationError" title="Link permanente para esta definição">¶</a></dt>
<dd><p>Classe base para erros de sintaxe relacionados a indentação incorreta. Esta é uma subclasse de <a class="reference internal" href="#SyntaxError" title="SyntaxError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">SyntaxError</span></code></a>.</p>
</dd></dl>

<dl class="py exception">
<dt id="TabError">
<em class="property">exception </em><code class="sig-name descname">TabError</code><a class="headerlink" href="#TabError" title="Link permanente para esta definição">¶</a></dt>
<dd><p>Levantada quando o indentação contém um uso inconsistente de tabulações e espaços. Esta é uma subclasse de <a class="reference internal" href="#IndentationError" title="IndentationError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">IndentationError</span></code></a>.</p>
</dd></dl>

<dl class="py exception">
<dt id="SystemError">
<em class="property">exception </em><code class="sig-name descname">SystemError</code><a class="headerlink" href="#SystemError" title="Link permanente para esta definição">¶</a></dt>
<dd><p>Levantada quando o interpretador encontra um erro interno, mas a situação não parece tão grave para fazer com que perca todas as esperanças. O valor associado é uma string que indica o que deu errado (em termos de baixo nível).</p>
<p>Você deve relatar isso ao autor ou mantenedor do seu interpretador Python. Certifique-se de relatar a versão do interpretador Python (<code class="docutils literal notranslate"><span class="pre">sys.version</span></code>; também é impresso no início de uma sessão Python interativa), a mensagem de erro exata (o valor associado da exceção) e se possível a fonte do programa que acionou o erro.</p>
</dd></dl>

<dl class="py exception">
<dt id="SystemExit">
<em class="property">exception </em><code class="sig-name descname">SystemExit</code><a class="headerlink" href="#SystemExit" title="Link permanente para esta definição">¶</a></dt>
<dd><p>Esta exceção é levantada pela função <a class="reference internal" href="sys.html#sys.exit" title="sys.exit"><code class="xref py py-func docutils literal notranslate"><span class="pre">sys.exit()</span></code></a>. Ele herda de <a class="reference internal" href="#BaseException" title="BaseException"><code class="xref py py-exc docutils literal notranslate"><span class="pre">BaseException</span></code></a> em vez de  <a class="reference internal" href="#Exception" title="Exception"><code class="xref py py-exc docutils literal notranslate"><span class="pre">Exception</span></code></a> para que não seja acidentalmente capturado pelo código que captura <a class="reference internal" href="#Exception" title="Exception"><code class="xref py py-exc docutils literal notranslate"><span class="pre">Exception</span></code></a>. Isso permite que a exceção se propague corretamente e faça com que o interpretador saia. Quando não é tratado, o interpretador Python sai; nenhum traceback (situação da pilha de execução) é impresso. O construtor aceita o mesmo argumento opcional passado para <a class="reference internal" href="sys.html#sys.exit" title="sys.exit"><code class="xref py py-func docutils literal notranslate"><span class="pre">sys.exit()</span></code></a>. Se o valor for um inteiro, ele especifica o status de saída do sistema (passado para a função C <code class="xref c c-func docutils literal notranslate"><span class="pre">exit()</span></code>); se for <code class="docutils literal notranslate"><span class="pre">None</span></code>, o status de saída é zero; se tiver outro tipo (como uma string), o valor do objeto é exibido e o status de saída é um.</p>
<p>Uma chamada para <a class="reference internal" href="sys.html#sys.exit" title="sys.exit"><code class="xref py py-func docutils literal notranslate"><span class="pre">sys.exit()</span></code></a> é traduzida em uma exceção para que os tratadores de limpeza (cláusulas <a class="reference internal" href="../reference/compound_stmts.html#finally"><code class="xref std std-keyword docutils literal notranslate"><span class="pre">finally</span></code></a> das instruções <a class="reference internal" href="../reference/compound_stmts.html#try"><code class="xref std std-keyword docutils literal notranslate"><span class="pre">try</span></code></a>) possam ser executados, e para que um depurador possa executar um script sem correr o risco de perder o controle. A função <a class="reference internal" href="os.html#os._exit" title="os._exit"><code class="xref py py-func docutils literal notranslate"><span class="pre">os._exit()</span></code></a> pode ser usada se for absolutamente necessário sair imediatamente (por exemplo, no processo filho após uma chamada para <a class="reference internal" href="os.html#os.fork" title="os.fork"><code class="xref py py-func docutils literal notranslate"><span class="pre">os.fork()</span></code></a>).</p>
<dl class="py attribute">
<dt id="SystemExit.code">
<code class="sig-name descname">code</code><a class="headerlink" href="#SystemExit.code" title="Link permanente para esta definição">¶</a></dt>
<dd><p>O status de saída ou mensagem de erro transmitida ao construtor. (O padrão é <code class="docutils literal notranslate"><span class="pre">None</span></code>.)</p>
</dd></dl>

</dd></dl>

<dl class="py exception">
<dt id="TypeError">
<em class="property">exception </em><code class="sig-name descname">TypeError</code><a class="headerlink" href="#TypeError" title="Link permanente para esta definição">¶</a></dt>
<dd><p>Levantada quando uma operação ou função é aplicada a um objeto de tipo inadequado. O valor associado é uma string que fornece detalhes sobre a incompatibilidade de tipo.</p>
<p>Essa exceção pode ser levantada pelo código do usuário para indicar que uma tentativa de operação em um objeto não é suportada e não deveria ser. Se um objeto deve ter suporte a uma dada operação, mas ainda não forneceu uma implementação, <a class="reference internal" href="#NotImplementedError" title="NotImplementedError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">NotImplementedError</span></code></a> é a exceção apropriada a ser levantada.</p>
<p>Passar argumentos do tipo errado (por exemplo, passar uma <a class="reference internal" href="stdtypes.html#list" title="list"><code class="xref py py-class docutils literal notranslate"><span class="pre">list</span></code></a> quando um <a class="reference internal" href="functions.html#int" title="int"><code class="xref py py-class docutils literal notranslate"><span class="pre">int</span></code></a> é esperado) deve resultar em uma <a class="reference internal" href="#TypeError" title="TypeError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">TypeError</span></code></a>, mas passar argumentos com o valor errado (por exemplo, um número fora limites esperados) deve resultar em uma <a class="reference internal" href="#ValueError" title="ValueError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">ValueError</span></code></a>.</p>
</dd></dl>

<dl class="py exception">
<dt id="UnboundLocalError">
<em class="property">exception </em><code class="sig-name descname">UnboundLocalError</code><a class="headerlink" href="#UnboundLocalError" title="Link permanente para esta definição">¶</a></dt>
<dd><p>Levantada quando uma referência é feita a uma variável local em uma função ou método, mas nenhum valor foi vinculado a essa variável. Esta é uma subclasse de <a class="reference internal" href="#NameError" title="NameError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">NameError</span></code></a>.</p>
</dd></dl>

<dl class="py exception">
<dt id="UnicodeError">
<em class="property">exception </em><code class="sig-name descname">UnicodeError</code><a class="headerlink" href="#UnicodeError" title="Link permanente para esta definição">¶</a></dt>
<dd><p>Levantada quando ocorre um erro de codificação ou decodificação relacionado ao Unicode. É uma subclasse de <a class="reference internal" href="#ValueError" title="ValueError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">ValueError</span></code></a>.</p>
<p><a class="reference internal" href="#UnicodeError" title="UnicodeError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">UnicodeError</span></code></a> possui atributos que descrevem o erro de codificação ou decodificação. Por exemplo, <code class="docutils literal notranslate"><span class="pre">err.object[err.start:err.end]</span></code> fornece a entrada inválida específica na qual o codec falhou.</p>
<dl class="py attribute">
<dt id="UnicodeError.encoding">
<code class="sig-name descname">encoding</code><a class="headerlink" href="#UnicodeError.encoding" title="Link permanente para esta definição">¶</a></dt>
<dd><p>O nome da codificação que levantou o erro.</p>
</dd></dl>

<dl class="py attribute">
<dt id="UnicodeError.reason">
<code class="sig-name descname">reason</code><a class="headerlink" href="#UnicodeError.reason" title="Link permanente para esta definição">¶</a></dt>
<dd><p>Uma string que descreve o erro de codec específico.</p>
</dd></dl>

<dl class="py attribute">
<dt id="UnicodeError.object">
<code class="sig-name descname">object</code><a class="headerlink" href="#UnicodeError.object" title="Link permanente para esta definição">¶</a></dt>
<dd><p>O objeto que o codec estava tentando codificar ou decodificar.</p>
</dd></dl>

<dl class="py attribute">
<dt id="UnicodeError.start">
<code class="sig-name descname">start</code><a class="headerlink" href="#UnicodeError.start" title="Link permanente para esta definição">¶</a></dt>
<dd><p>O primeiro índice de dados inválidos em <a class="reference internal" href="functions.html#object" title="object"><code class="xref py py-attr docutils literal notranslate"><span class="pre">object</span></code></a>.</p>
</dd></dl>

<dl class="py attribute">
<dt id="UnicodeError.end">
<code class="sig-name descname">end</code><a class="headerlink" href="#UnicodeError.end" title="Link permanente para esta definição">¶</a></dt>
<dd><p>O índice após os últimos dados inválidos em <a class="reference internal" href="functions.html#object" title="object"><code class="xref py py-attr docutils literal notranslate"><span class="pre">object</span></code></a>.</p>
</dd></dl>

</dd></dl>

<dl class="py exception">
<dt id="UnicodeEncodeError">
<em class="property">exception </em><code class="sig-name descname">UnicodeEncodeError</code><a class="headerlink" href="#UnicodeEncodeError" title="Link permanente para esta definição">¶</a></dt>
<dd><p>Levantada quando ocorre um erro relacionado ao Unicode durante a codificação. É uma subclasse de <a class="reference internal" href="#UnicodeError" title="UnicodeError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">UnicodeError</span></code></a>.</p>
</dd></dl>

<dl class="py exception">
<dt id="UnicodeDecodeError">
<em class="property">exception </em><code class="sig-name descname">UnicodeDecodeError</code><a class="headerlink" href="#UnicodeDecodeError" title="Link permanente para esta definição">¶</a></dt>
<dd><p>Levantada quando ocorre um erro relacionado ao Unicode durante a decodificação. É uma subclasse de <a class="reference internal" href="#UnicodeError" title="UnicodeError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">UnicodeError</span></code></a>.</p>
</dd></dl>

<dl class="py exception">
<dt id="UnicodeTranslateError">
<em class="property">exception </em><code class="sig-name descname">UnicodeTranslateError</code><a class="headerlink" href="#UnicodeTranslateError" title="Link permanente para esta definição">¶</a></dt>
<dd><p>Levantada quando ocorre um erro relacionado ao Unicode durante a tradução. É uma subclasse de <a class="reference internal" href="#UnicodeError" title="UnicodeError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">UnicodeError</span></code></a>.</p>
</dd></dl>

<dl class="py exception">
<dt id="ValueError">
<em class="property">exception </em><code class="sig-name descname">ValueError</code><a class="headerlink" href="#ValueError" title="Link permanente para esta definição">¶</a></dt>
<dd><p>Levantada quando uma operação ou função recebe um argumento que tem o tipo certo, mas um valor inadequado, e a situação não é descrita por uma exceção mais precisa, como <a class="reference internal" href="#IndexError" title="IndexError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">IndexError</span></code></a>.</p>
</dd></dl>

<dl class="py exception">
<dt id="ZeroDivisionError">
<em class="property">exception </em><code class="sig-name descname">ZeroDivisionError</code><a class="headerlink" href="#ZeroDivisionError" title="Link permanente para esta definição">¶</a></dt>
<dd><p>Levantada quando o segundo argumento de uma divisão ou operação de módulo é zero. O valor associado é uma string que indica o tipo dos operandos e a operação.</p>
</dd></dl>

<p>As seguintes exceções são mantidas para compatibilidade com versões anteriores; a partir do Python 3.3, eles são apelidos de <a class="reference internal" href="#OSError" title="OSError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">OSError</span></code></a>.</p>
<dl class="py exception">
<dt id="EnvironmentError">
<em class="property">exception </em><code class="sig-name descname">EnvironmentError</code><a class="headerlink" href="#EnvironmentError" title="Link permanente para esta definição">¶</a></dt>
<dd></dd></dl>

<dl class="py exception">
<dt id="IOError">
<em class="property">exception </em><code class="sig-name descname">IOError</code><a class="headerlink" href="#IOError" title="Link permanente para esta definição">¶</a></dt>
<dd></dd></dl>

<dl class="py exception">
<dt id="WindowsError">
<em class="property">exception </em><code class="sig-name descname">WindowsError</code><a class="headerlink" href="#WindowsError" title="Link permanente para esta definição">¶</a></dt>
<dd><p>Disponível apenas no Windows.</p>
</dd></dl>

<section id="os-exceptions">
<h3>Exceções de sistema operacional<a class="headerlink" href="#os-exceptions" title="Link permanente para este título">¶</a></h3>
<p>As seguintes exceções são subclasses de <a class="reference internal" href="#OSError" title="OSError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">OSError</span></code></a>, elas são levantadas dependendo do código de erro do sistema.</p>
<dl class="py exception">
<dt id="BlockingIOError">
<em class="property">exception </em><code class="sig-name descname">BlockingIOError</code><a class="headerlink" href="#BlockingIOError" title="Link permanente para esta definição">¶</a></dt>
<dd><p>Raised when an operation would block on an object (e.g. socket) set
for non-blocking operation.
Corresponds to <code class="xref c c-data docutils literal notranslate"><span class="pre">errno</span></code> <a class="reference internal" href="errno.html#errno.EAGAIN" title="errno.EAGAIN"><code class="xref py py-data docutils literal notranslate"><span class="pre">EAGAIN</span></code></a>, <a class="reference internal" href="errno.html#errno.EALREADY" title="errno.EALREADY"><code class="xref py py-data docutils literal notranslate"><span class="pre">EALREADY</span></code></a>,
<a class="reference internal" href="errno.html#errno.EWOULDBLOCK" title="errno.EWOULDBLOCK"><code class="xref py py-data docutils literal notranslate"><span class="pre">EWOULDBLOCK</span></code></a> and <a class="reference internal" href="errno.html#errno.EINPROGRESS" title="errno.EINPROGRESS"><code class="xref py py-data docutils literal notranslate"><span class="pre">EINPROGRESS</span></code></a>.</p>
<p>Além daquelas de <a class="reference internal" href="#OSError" title="OSError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">OSError</span></code></a>, <a class="reference internal" href="#BlockingIOError" title="BlockingIOError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">BlockingIOError</span></code></a> pode ter mais um atributo:</p>
<dl class="py attribute">
<dt id="BlockingIOError.characters_written">
<code class="sig-name descname">characters_written</code><a class="headerlink" href="#BlockingIOError.characters_written" title="Link permanente para esta definição">¶</a></dt>
<dd><p>Um inteiro contendo o número de caracteres gravados no fluxo antes de ser bloqueado. Este atributo está disponível ao usar as classes de E/S em buffer do módulo <a class="reference internal" href="io.html#module-io" title="io: Core tools for working with streams."><code class="xref py py-mod docutils literal notranslate"><span class="pre">io</span></code></a>.</p>
</dd></dl>

</dd></dl>

<dl class="py exception">
<dt id="ChildProcessError">
<em class="property">exception </em><code class="sig-name descname">ChildProcessError</code><a class="headerlink" href="#ChildProcessError" title="Link permanente para esta definição">¶</a></dt>
<dd><p>Raised when an operation on a child process failed.
Corresponds to <code class="xref c c-data docutils literal notranslate"><span class="pre">errno</span></code> <a class="reference internal" href="errno.html#errno.ECHILD" title="errno.ECHILD"><code class="xref py py-data docutils literal notranslate"><span class="pre">ECHILD</span></code></a>.</p>
</dd></dl>

<dl class="py exception">
<dt id="ConnectionError">
<em class="property">exception </em><code class="sig-name descname">ConnectionError</code><a class="headerlink" href="#ConnectionError" title="Link permanente para esta definição">¶</a></dt>
<dd><p>Uma classe base para problemas relacionados à conexão.</p>
<p>Suas subclasses são <a class="reference internal" href="#BrokenPipeError" title="BrokenPipeError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">BrokenPipeError</span></code></a>, <a class="reference internal" href="#ConnectionAbortedError" title="ConnectionAbortedError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">ConnectionAbortedError</span></code></a>, <a class="reference internal" href="#ConnectionRefusedError" title="ConnectionRefusedError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">ConnectionRefusedError</span></code></a> e <a class="reference internal" href="#ConnectionResetError" title="ConnectionResetError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">ConnectionResetError</span></code></a>.</p>
</dd></dl>

<dl class="py exception">
<dt id="BrokenPipeError">
<em class="property">exception </em><code class="sig-name descname">BrokenPipeError</code><a class="headerlink" href="#BrokenPipeError" title="Link permanente para esta definição">¶</a></dt>
<dd><p>A subclass of <a class="reference internal" href="#ConnectionError" title="ConnectionError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">ConnectionError</span></code></a>, raised when trying to write on a
pipe while the other end has been closed, or trying to write on a socket
which has been shutdown for writing.
Corresponds to <code class="xref c c-data docutils literal notranslate"><span class="pre">errno</span></code> <a class="reference internal" href="errno.html#errno.EPIPE" title="errno.EPIPE"><code class="xref py py-data docutils literal notranslate"><span class="pre">EPIPE</span></code></a> and <a class="reference internal" href="errno.html#errno.ESHUTDOWN" title="errno.ESHUTDOWN"><code class="xref py py-data docutils literal notranslate"><span class="pre">ESHUTDOWN</span></code></a>.</p>
</dd></dl>

<dl class="py exception">
<dt id="ConnectionAbortedError">
<em class="property">exception </em><code class="sig-name descname">ConnectionAbortedError</code><a class="headerlink" href="#ConnectionAbortedError" title="Link permanente para esta definição">¶</a></dt>
<dd><p>A subclass of <a class="reference internal" href="#ConnectionError" title="ConnectionError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">ConnectionError</span></code></a>, raised when a connection attempt
is aborted by the peer.
Corresponds to <code class="xref c c-data docutils literal notranslate"><span class="pre">errno</span></code> <a class="reference internal" href="errno.html#errno.ECONNABORTED" title="errno.ECONNABORTED"><code class="xref py py-data docutils literal notranslate"><span class="pre">ECONNABORTED</span></code></a>.</p>
</dd></dl>

<dl class="py exception">
<dt id="ConnectionRefusedError">
<em class="property">exception </em><code class="sig-name descname">ConnectionRefusedError</code><a class="headerlink" href="#ConnectionRefusedError" title="Link permanente para esta definição">¶</a></dt>
<dd><p>A subclass of <a class="reference internal" href="#ConnectionError" title="ConnectionError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">ConnectionError</span></code></a>, raised when a connection attempt
is refused by the peer.
Corresponds to <code class="xref c c-data docutils literal notranslate"><span class="pre">errno</span></code> <a class="reference internal" href="errno.html#errno.ECONNREFUSED" title="errno.ECONNREFUSED"><code class="xref py py-data docutils literal notranslate"><span class="pre">ECONNREFUSED</span></code></a>.</p>
</dd></dl>

<dl class="py exception">
<dt id="ConnectionResetError">
<em class="property">exception </em><code class="sig-name descname">ConnectionResetError</code><a class="headerlink" href="#ConnectionResetError" title="Link permanente para esta definição">¶</a></dt>
<dd><p>A subclass of <a class="reference internal" href="#ConnectionError" title="ConnectionError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">ConnectionError</span></code></a>, raised when a connection is
reset by the peer.
Corresponds to <code class="xref c c-data docutils literal notranslate"><span class="pre">errno</span></code> <a class="reference internal" href="errno.html#errno.ECONNRESET" title="errno.ECONNRESET"><code class="xref py py-data docutils literal notranslate"><span class="pre">ECONNRESET</span></code></a>.</p>
</dd></dl>

<dl class="py exception">
<dt id="FileExistsError">
<em class="property">exception </em><code class="sig-name descname">FileExistsError</code><a class="headerlink" href="#FileExistsError" title="Link permanente para esta definição">¶</a></dt>
<dd><p>Raised when trying to create a file or directory which already exists.
Corresponds to <code class="xref c c-data docutils literal notranslate"><span class="pre">errno</span></code> <a class="reference internal" href="errno.html#errno.EEXIST" title="errno.EEXIST"><code class="xref py py-data docutils literal notranslate"><span class="pre">EEXIST</span></code></a>.</p>
</dd></dl>

<dl class="py exception">
<dt id="FileNotFoundError">
<em class="property">exception </em><code class="sig-name descname">FileNotFoundError</code><a class="headerlink" href="#FileNotFoundError" title="Link permanente para esta definição">¶</a></dt>
<dd><p>Raised when a file or directory is requested but doesn’t exist.
Corresponds to <code class="xref c c-data docutils literal notranslate"><span class="pre">errno</span></code> <a class="reference internal" href="errno.html#errno.ENOENT" title="errno.ENOENT"><code class="xref py py-data docutils literal notranslate"><span class="pre">ENOENT</span></code></a>.</p>
</dd></dl>

<dl class="py exception">
<dt id="InterruptedError">
<em class="property">exception </em><code class="sig-name descname">InterruptedError</code><a class="headerlink" href="#InterruptedError" title="Link permanente para esta definição">¶</a></dt>
<dd><p>Levantada quando uma chamada do sistema é interrompida por um sinal de entrada. Corresponde a <code class="xref c c-data docutils literal notranslate"><span class="pre">errno</span></code> <a class="reference internal" href="errno.html#errno.EINTR" title="errno.EINTR"><code class="xref py py-data docutils literal notranslate"><span class="pre">EINTR</span></code></a>.</p>
<div class="versionchanged">
<p><span class="versionmodified changed">Alterado na versão 3.5: </span>Python agora tenta novamente chamadas de sistema quando uma <em>syscall</em> é interrompida por um sinal, exceto se o tratador de sinal levanta uma exceção (veja <span class="target" id="index-20"></span><a class="pep reference external" href="https://www.python.org/dev/peps/pep-0475"><strong>PEP 475</strong></a> para a justificativa), em vez de levantar <a class="reference internal" href="#InterruptedError" title="InterruptedError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">InterruptedError</span></code></a>.</p>
</div>
</dd></dl>

<dl class="py exception">
<dt id="IsADirectoryError">
<em class="property">exception </em><code class="sig-name descname">IsADirectoryError</code><a class="headerlink" href="#IsADirectoryError" title="Link permanente para esta definição">¶</a></dt>
<dd><p>Raised when a file operation (such as <a class="reference internal" href="os.html#os.remove" title="os.remove"><code class="xref py py-func docutils literal notranslate"><span class="pre">os.remove()</span></code></a>) is requested
on a directory.
Corresponds to <code class="xref c c-data docutils literal notranslate"><span class="pre">errno</span></code> <a class="reference internal" href="errno.html#errno.EISDIR" title="errno.EISDIR"><code class="xref py py-data docutils literal notranslate"><span class="pre">EISDIR</span></code></a>.</p>
</dd></dl>

<dl class="py exception">
<dt id="NotADirectoryError">
<em class="property">exception </em><code class="sig-name descname">NotADirectoryError</code><a class="headerlink" href="#NotADirectoryError" title="Link permanente para esta definição">¶</a></dt>
<dd><p>Raised when a directory operation (such as <a class="reference internal" href="os.html#os.listdir" title="os.listdir"><code class="xref py py-func docutils literal notranslate"><span class="pre">os.listdir()</span></code></a>) is requested on
something which is not a directory.  On most POSIX platforms, it may also be
raised if an operation attempts to open or traverse a non-directory file as if
it were a directory.
Corresponds to <code class="xref c c-data docutils literal notranslate"><span class="pre">errno</span></code> <a class="reference internal" href="errno.html#errno.ENOTDIR" title="errno.ENOTDIR"><code class="xref py py-data docutils literal notranslate"><span class="pre">ENOTDIR</span></code></a>.</p>
</dd></dl>

<dl class="py exception">
<dt id="PermissionError">
<em class="property">exception </em><code class="sig-name descname">PermissionError</code><a class="headerlink" href="#PermissionError" title="Link permanente para esta definição">¶</a></dt>
<dd><p>Raised when trying to run an operation without the adequate access
rights - for example filesystem permissions.
Corresponds to <code class="xref c c-data docutils literal notranslate"><span class="pre">errno</span></code> <a class="reference internal" href="errno.html#errno.EACCES" title="errno.EACCES"><code class="xref py py-data docutils literal notranslate"><span class="pre">EACCES</span></code></a> and <a class="reference internal" href="errno.html#errno.EPERM" title="errno.EPERM"><code class="xref py py-data docutils literal notranslate"><span class="pre">EPERM</span></code></a>.</p>
</dd></dl>

<dl class="py exception">
<dt id="ProcessLookupError">
<em class="property">exception </em><code class="sig-name descname">ProcessLookupError</code><a class="headerlink" href="#ProcessLookupError" title="Link permanente para esta definição">¶</a></dt>
<dd><p>Raised when a given process doesn’t exist.
Corresponds to <code class="xref c c-data docutils literal notranslate"><span class="pre">errno</span></code> <a class="reference internal" href="errno.html#errno.ESRCH" title="errno.ESRCH"><code class="xref py py-data docutils literal notranslate"><span class="pre">ESRCH</span></code></a>.</p>
</dd></dl>

<dl class="py exception">
<dt id="TimeoutError">
<em class="property">exception </em><code class="sig-name descname">TimeoutError</code><a class="headerlink" href="#TimeoutError" title="Link permanente para esta definição">¶</a></dt>
<dd><p>Raised when a system function timed out at the system level.
Corresponds to <code class="xref c c-data docutils literal notranslate"><span class="pre">errno</span></code> <a class="reference internal" href="errno.html#errno.ETIMEDOUT" title="errno.ETIMEDOUT"><code class="xref py py-data docutils literal notranslate"><span class="pre">ETIMEDOUT</span></code></a>.</p>
</dd></dl>

<div class="versionadded">
<p><span class="versionmodified added">Novo na versão 3.3: </span>Todas as subclasses de <a class="reference internal" href="#OSError" title="OSError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">OSError</span></code></a> acima foram adicionadas.</p>
</div>
<div class="admonition seealso">
<p class="admonition-title">Ver também</p>
<p><span class="target" id="index-8"></span><a class="pep reference external" href="https://www.python.org/dev/peps/pep-3151"><strong>PEP 3151</strong></a> - Reworking the OS and IO exception hierarchy</p>
</div>
</section>
</section>
<section id="warnings">
<span id="warning-categories-as-exceptions"></span><h2>Avisos<a class="headerlink" href="#warnings" title="Link permanente para este título">¶</a></h2>
<p>As seguintes exceções são usadas como categorias de aviso; veja a documentação de <a class="reference internal" href="warnings.html#warning-categories"><span class="std std-ref">Categorias de avisos</span></a> para mais detalhes.</p>
<dl class="py exception">
<dt id="Warning">
<em class="property">exception </em><code class="sig-name descname">Warning</code><a class="headerlink" href="#Warning" title="Link permanente para esta definição">¶</a></dt>
<dd><p>Classe base para categorias de aviso.</p>
</dd></dl>

<dl class="py exception">
<dt id="UserWarning">
<em class="property">exception </em><code class="sig-name descname">UserWarning</code><a class="headerlink" href="#UserWarning" title="Link permanente para esta definição">¶</a></dt>
<dd><p>Classe base para avisos gerados pelo código do usuário.</p>
</dd></dl>

<dl class="py exception">
<dt id="DeprecationWarning">
<em class="property">exception </em><code class="sig-name descname">DeprecationWarning</code><a class="headerlink" href="#DeprecationWarning" title="Link permanente para esta definição">¶</a></dt>
<dd><p>Classe base para avisos sobre recursos descontinuados quando esses avisos se destinam a outros desenvolvedores Python.</p>
<p>Ignorado pelos filtros de aviso padrão, exceto no módulo <code class="docutils literal notranslate"><span class="pre">__main__</span></code> (<span class="target" id="index-21"></span><a class="pep reference external" href="https://www.python.org/dev/peps/pep-0565"><strong>PEP 565</strong></a>). Habilitar o <a class="reference internal" href="devmode.html#devmode"><span class="std std-ref">Modo de Desenvolvimento do Python</span></a> mostra este aviso.</p>
<p>The deprecation policy is described in <span class="target" id="index-10"></span><a class="pep reference external" href="https://www.python.org/dev/peps/pep-0387"><strong>PEP 387</strong></a>.</p>
</dd></dl>

<dl class="py exception">
<dt id="PendingDeprecationWarning">
<em class="property">exception </em><code class="sig-name descname">PendingDeprecationWarning</code><a class="headerlink" href="#PendingDeprecationWarning" title="Link permanente para esta definição">¶</a></dt>
<dd><p>Classe base para avisos sobre recursos que foram descontinuados e devem ser descontinuados no futuro, mas não foram descontinuados ainda.</p>
<p>Esta classe raramente é usada para emitir um aviso sobre uma possível descontinuação futura, é incomum, e <a class="reference internal" href="#DeprecationWarning" title="DeprecationWarning"><code class="xref py py-exc docutils literal notranslate"><span class="pre">DeprecationWarning</span></code></a> é preferível para descontinuações já ativas.</p>
<p>Ignorado pelos filtros de aviso padrão. Habilitar o <a class="reference internal" href="devmode.html#devmode"><span class="std std-ref">Modo de Desenvolvimento do Python</span></a> mostra este aviso.</p>
<p>The deprecation policy is described in <span class="target" id="index-11"></span><a class="pep reference external" href="https://www.python.org/dev/peps/pep-0387"><strong>PEP 387</strong></a>.</p>
</dd></dl>

<dl class="py exception">
<dt id="SyntaxWarning">
<em class="property">exception </em><code class="sig-name descname">SyntaxWarning</code><a class="headerlink" href="#SyntaxWarning" title="Link permanente para esta definição">¶</a></dt>
<dd><p>Classe base para avisos sobre sintaxe duvidosa.</p>
</dd></dl>

<dl class="py exception">
<dt id="RuntimeWarning">
<em class="property">exception </em><code class="sig-name descname">RuntimeWarning</code><a class="headerlink" href="#RuntimeWarning" title="Link permanente para esta definição">¶</a></dt>
<dd><p>Classe base para avisos sobre comportamento duvidoso de tempo de execução.</p>
</dd></dl>

<dl class="py exception">
<dt id="FutureWarning">
<em class="property">exception </em><code class="sig-name descname">FutureWarning</code><a class="headerlink" href="#FutureWarning" title="Link permanente para esta definição">¶</a></dt>
<dd><p>Classe base para avisos sobre recursos descontinuados quando esses avisos se destinam a usuários finais de aplicações escritas em Python.</p>
</dd></dl>

<dl class="py exception">
<dt id="ImportWarning">
<em class="property">exception </em><code class="sig-name descname">ImportWarning</code><a class="headerlink" href="#ImportWarning" title="Link permanente para esta definição">¶</a></dt>
<dd><p>Classe base para avisos sobre prováveis erros na importação de módulos.</p>
<p>Ignorado pelos filtros de aviso padrão. Habilitar o <a class="reference internal" href="devmode.html#devmode"><span class="std std-ref">Modo de Desenvolvimento do Python</span></a> mostra este aviso.</p>
</dd></dl>

<dl class="py exception">
<dt id="UnicodeWarning">
<em class="property">exception </em><code class="sig-name descname">UnicodeWarning</code><a class="headerlink" href="#UnicodeWarning" title="Link permanente para esta definição">¶</a></dt>
<dd><p>Classe base para avisos relacionados a Unicode.</p>
</dd></dl>

<dl class="py exception">
<dt id="EncodingWarning">
<em class="property">exception </em><code class="sig-name descname">EncodingWarning</code><a class="headerlink" href="#EncodingWarning" title="Link permanente para esta definição">¶</a></dt>
<dd><p>Classe base para avisos relacionados a codificações.</p>
<p>Veja <a class="reference internal" href="io.html#io-encoding-warning"><span class="std std-ref">Opt-in EncodingWarning</span></a> para detalhes.</p>
<div class="versionadded">
<p><span class="versionmodified added">Novo na versão 3.10.</span></p>
</div>
</dd></dl>

<dl class="py exception">
<dt id="BytesWarning">
<em class="property">exception </em><code class="sig-name descname">BytesWarning</code><a class="headerlink" href="#BytesWarning" title="Link permanente para esta definição">¶</a></dt>
<dd><p>Classe base para avisos relacionados a <a class="reference internal" href="stdtypes.html#bytes" title="bytes"><code class="xref py py-class docutils literal notranslate"><span class="pre">bytes</span></code></a> e <a class="reference internal" href="stdtypes.html#bytearray" title="bytearray"><code class="xref py py-class docutils literal notranslate"><span class="pre">bytearray</span></code></a>.</p>
</dd></dl>

<dl class="py exception">
<dt id="ResourceWarning">
<em class="property">exception </em><code class="sig-name descname">ResourceWarning</code><a class="headerlink" href="#ResourceWarning" title="Link permanente para esta definição">¶</a></dt>
<dd><p>Classe base para avisos relacionados a uso de recursos.</p>
<p>Ignorado pelos filtros de aviso padrão. Habilitar o <a class="reference internal" href="devmode.html#devmode"><span class="std std-ref">Modo de Desenvolvimento do Python</span></a> mostra este aviso.</p>
<div class="versionadded">
<p><span class="versionmodified added">Novo na versão 3.2.</span></p>
</div>
</dd></dl>

</section>
<section id="exception-hierarchy">
<h2>Hierarquia das exceções<a class="headerlink" href="#exception-hierarchy" title="Link permanente para este título">¶</a></h2>
<p>A hierarquia de classes para exceções embutidas é:</p>
<div class="highlight-python3 notranslate"><div class="highlight"><pre><span></span><span class="ne">BaseException</span>
 <span class="o">+--</span> <span class="ne">SystemExit</span>
 <span class="o">+--</span> <span class="ne">KeyboardInterrupt</span>
 <span class="o">+--</span> <span class="ne">GeneratorExit</span>
 <span class="o">+--</span> <span class="ne">Exception</span>
      <span class="o">+--</span> <span class="ne">StopIteration</span>
      <span class="o">+--</span> <span class="ne">StopAsyncIteration</span>
      <span class="o">+--</span> <span class="ne">ArithmeticError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">FloatingPointError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">OverflowError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">ZeroDivisionError</span>
      <span class="o">+--</span> <span class="ne">AssertionError</span>
      <span class="o">+--</span> <span class="ne">AttributeError</span>
      <span class="o">+--</span> <span class="ne">BufferError</span>
      <span class="o">+--</span> <span class="ne">EOFError</span>
      <span class="o">+--</span> <span class="ne">ImportError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">ModuleNotFoundError</span>
      <span class="o">+--</span> <span class="ne">LookupError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">IndexError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">KeyError</span>
      <span class="o">+--</span> <span class="ne">MemoryError</span>
      <span class="o">+--</span> <span class="ne">NameError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">UnboundLocalError</span>
      <span class="o">+--</span> <span class="ne">OSError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">BlockingIOError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">ChildProcessError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">ConnectionError</span>
      <span class="o">|</span>    <span class="o">|</span>    <span class="o">+--</span> <span class="ne">BrokenPipeError</span>
      <span class="o">|</span>    <span class="o">|</span>    <span class="o">+--</span> <span class="ne">ConnectionAbortedError</span>
      <span class="o">|</span>    <span class="o">|</span>    <span class="o">+--</span> <span class="ne">ConnectionRefusedError</span>
      <span class="o">|</span>    <span class="o">|</span>    <span class="o">+--</span> <span class="ne">ConnectionResetError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">FileExistsError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">FileNotFoundError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">InterruptedError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">IsADirectoryError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">NotADirectoryError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">PermissionError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">ProcessLookupError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">TimeoutError</span>
      <span class="o">+--</span> <span class="ne">ReferenceError</span>
      <span class="o">+--</span> <span class="ne">RuntimeError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">NotImplementedError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">RecursionError</span>
      <span class="o">+--</span> <span class="ne">SyntaxError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">IndentationError</span>
      <span class="o">|</span>         <span class="o">+--</span> <span class="ne">TabError</span>
      <span class="o">+--</span> <span class="ne">SystemError</span>
      <span class="o">+--</span> <span class="ne">TypeError</span>
      <span class="o">+--</span> <span class="ne">ValueError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">UnicodeError</span>
      <span class="o">|</span>         <span class="o">+--</span> <span class="ne">UnicodeDecodeError</span>
      <span class="o">|</span>         <span class="o">+--</span> <span class="ne">UnicodeEncodeError</span>
      <span class="o">|</span>         <span class="o">+--</span> <span class="ne">UnicodeTranslateError</span>
      <span class="o">+--</span> <span class="ne">Warning</span>
           <span class="o">+--</span> <span class="ne">DeprecationWarning</span>
           <span class="o">+--</span> <span class="ne">PendingDeprecationWarning</span>
           <span class="o">+--</span> <span class="ne">RuntimeWarning</span>
           <span class="o">+--</span> <span class="ne">SyntaxWarning</span>
           <span class="o">+--</span> <span class="ne">UserWarning</span>
           <span class="o">+--</span> <span class="ne">FutureWarning</span>
           <span class="o">+--</span> <span class="ne">ImportWarning</span>
           <span class="o">+--</span> <span class="ne">UnicodeWarning</span>
           <span class="o">+--</span> <span class="ne">BytesWarning</span>
           <span class="o">+--</span> <span class="ne">EncodingWarning</span>
           <span class="o">+--</span> <span class="ne">ResourceWarning</span>
</pre></div>
</div>
</section>
</section>


            <div class="clearer"></div>
          </div>
        </div>
      </div>
      <div class="sphinxsidebar" role="navigation" aria-label="main navigation">
        <div class="sphinxsidebarwrapper">
  <h3><a href="../contents.html">Tabela de Conteúdo</a></h3>
  <ul>
<li><a class="reference internal" href="#">Exceções embutidas</a><ul>
<li><a class="reference internal" href="#exception-context">Exception context</a></li>
<li><a class="reference internal" href="#inheriting-from-built-in-exceptions">Inheriting from built-in exceptions</a></li>
<li><a class="reference internal" href="#base-classes">Classes base</a></li>
<li><a class="reference internal" href="#concrete-exceptions">Exceções concretas</a><ul>
<li><a class="reference internal" href="#os-exceptions">Exceções de sistema operacional</a></li>
</ul>
</li>
<li><a class="reference internal" href="#warnings">Avisos</a></li>
<li><a class="reference internal" href="#exception-hierarchy">Hierarquia das exceções</a></li>
</ul>
</li>
</ul>

  <h4>Tópico anterior</h4>
  <p class="topless"><a href="stdtypes.html"
                        title="capítulo anterior">Tipos embutidos</a></p>
  <h4>Próximo tópico</h4>
  <p class="topless"><a href="text.html"
                        title="próximo capítulo">Serviços de Processamento de Texto</a></p>
  <div role="note" aria-label="source link">
    <h3>Esta página</h3>
    <ul class="this-page-menu">
      <li><a href="../bugs.html">Relatar um erro</a></li>
      <li>
        <a href="https://github.com/python/cpython/blob/3.10/Doc/library/exceptions.rst"
            rel="nofollow">Exibir código-fonte
        </a>
      </li>
    </ul>
  </div>
        </div>
      </div>
      <div class="clearer"></div>
    </div>  
    <div class="related" role="navigation" aria-label="related navigation">
      <h3>Navegação</h3>
      <ul>
        <li class="right" style="margin-right: 10px">
          <a href="../genindex.html" title="Índice geral"
             >índice</a></li>
        <li class="right" >
          <a href="../py-modindex.html" title="Índice de Módulos Python"
             >módulos</a> |</li>
        <li class="right" >
          <a href="text.html" title="Serviços de Processamento de Texto"
             >próximo</a> |</li>
        <li class="right" >
          <a href="stdtypes.html" title="Tipos embutidos"
             >anterior</a> |</li>

          <li><img src="../_static/py.svg" alt="python logo" style="vertical-align: middle; margin-top: -1px"/></li>
          <li><a href="https://www.python.org/">Python</a> &#187;</li>
          <li class="switchers">
            <div class="language_switcher_placeholder"></div>
            <div class="version_switcher_placeholder"></div>
          </li>
          <li>
              
          </li>
    <li id="cpython-language-and-version">
      <a href="../index.html">3.10.4 Documentation</a> &#187;
    </li>

          <li class="nav-item nav-item-1"><a href="index.html" >A Biblioteca Padrão do Python</a> &#187;</li>
        <li class="nav-item nav-item-this"><a href="">Exceções embutidas</a></li>
                <li class="right">
                    

    <div class="inline-search" role="search">
        <form class="inline-search" action="../search.html" method="get">
          <input placeholder="Busca rápida" aria-label="Busca rápida" type="text" name="q" />
          <input type="submit" value="Ir" />
          <input type="hidden" name="check_keywords" value="yes" />
          <input type="hidden" name="area" value="default" />
        </form>
    </div>
                     |
                </li>
            
      </ul>
    </div>  
    <div class="footer">
    &copy; <a href="../copyright.html">Direitos autorais</a> 2001-2022, Python Software Foundation.
    <br />
    This page is licensed under the Python Software Foundation License Version 2.
    <br />
    Examples, recipes, and other code in the documentation are additionally licensed under the Zero Clause BSD License.
    <br />
    See <a href="/license.html">History and License</a> for more information.<br />
    <br />

    The Python Software Foundation is a non-profit corporation.
<a href="https://www.python.org/psf/donations/">Please donate.</a>
<br />
    <br />

    Última atualização em jun. 04, 2022.
    <a href="/bugs.html">Found a bug</a>?
    <br />

    Created using <a href="https://www.sphinx-doc.org/">Sphinx</a> 3.4.3.
    </div>

  </body>
</html>